### ISSUE TITLE
PID

### ISSUE THREAD

**Issue by azyth** [Ohmbrewer/ohmbrewer#10]
The PID algorithm needs to be functional and hopefully integrated into the system.

**Comment by azyth** [comment]
I have found a functional PID library for the spark, it is using  analog in/out so depending on specifics we may need to change a few things around. https://github.com/dnrce/Spark-PID we should try to flash this to a spark at somepoint soon. 

also available in the online IDE for spark under libraries. if you search PID

**Comment by kyleoliveira** [comment]
I'm going to go ahead and close this. We'll want to break this into more actionable Issues in the Rhizomes repo.
