### ISSUE TITLE
HOPS - Hardware 

### ISSUE THREAD

**Issue by azyth** [Ohmbrewer/ohmbrewer#13]
status tracker for the hardware unit progress

V1 
support the mash and boil. with switches for:
mash heat
boil heat
rims pump
m2b pump

temp probes for
mash
rims
boil

**Comment by azyth** [comment]
current status: working on box layout and need a few more parts before i can asseble the test unit. 

also need to test the switch voltage for the DPDTs

**Comment by azyth** [comment]
Need a new order of parts , but I shoudl order the correct ones this time. 

and will have to wait for REV to get them for us now.

**Comment by kyleoliveira** [comment]
@azyth 
How we lookin' dude?

**Comment by azyth** [comment]
HOPS unit is wired up and awaiting some testing now, pump switches are not installed yet, need to test the SSRs i got to pump the switch power up from DC to AC for the contactor switches

**Comment by kyleoliveira** [comment]
I'm going to go ahead and close this. We'll want to create more actionable Issues in the HOPS repo for HOPS stuff.
