### ISSUE TITLE
Update Sprout communications methods according to new Rhizome API

### ISSUE THREAD

**Issue by kyleoliveira** [Ohmbrewer/ohmbrewer#96]
We've refactored out the need to send an explicit ID to create a new Sprout on the Rhizome, so we'll need to update our lib to reflect this change.

See Ohmbrewer/rhizome#77

**Comment by kathomas921** [comment]
How does this change work on the rhizome end? Does this mean we never have to enter a device ID to create a sprout on the rhizome, or it's just not required upon rhizome creation?

**Comment by kyleoliveira** [comment]
The change has already occurred on the Rhizome end (check out the linked PR). On the Ohmbrewer (web app) end, we need to modify the Sprout library method(s) so that it doesn't send an ID as part of the call that's made when adding a Sprout to the Rhizome.

I think we pretty much just need to change [this](https://github.com/Ohmbrewer/ohmbrewer/blob/master/lib/rhizome_interfaces/sprout/sprout.rb#L70) so that it doesn't include the ID. You could then test it by either:
1) Running a Schedule and watching the string that's produced when the update message is sent (this would require some puts statements and probably some commenting out)
2) Opening up the Rails console (rails -c), looking up some existing tasks for a batch (b), and calling b.task.sprout.to_add_args_str.

Probably would go with (2). If it doesn't work exactly like that and you're having a hard time figuring it out, ping me (I'm doing this off the top of my head). Either way, verify that the string that would be sent out matches what's in the API reference in the Rhizome manual sans the ID (we haven't updated the manual entry yet).
